/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * payreco
 * API for payreco app
 * OpenAPI spec version: 1.0
 */
import { rest } from "msw";

export const getCompaniesMock = () =>
  Array.from({ length: 3 }, (_, i) => i + 1).map((_, i) => ({
    id: "companyId" + (i + 1),
    name: "株式会社" + ["abc", "cde", "efg"][i],
    hourly_wage_system: i % 2 === 0 ? true : false,
    wage_amount: i % 2 === 0 ? 10 : null,
    currency_type: ["米ドル", "ユーロ", "英ポンド"][i],
    user_id: "userId1",
    deleted_at: null,
    created_at: new Date(),
    updated_at: new Date(),
  }));

export const getCompaniesMSW = () => [
  rest.get("*/companies", (_req, res, ctx) => {
    return res(ctx.json(getCompaniesMock()));
  }),
];
