/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * payreco
 * API for payreco app
 * OpenAPI spec version: 1.0
 */
import { rest } from "msw";

export const getMockUser1 = () => ({
  id: "userId",
  uid: "aafjkdfenoWFAGRHR",
  name: "Tanaka",
  target_amount: null,
  created_at: new Date(),
  updated_at: new Date(),
});

export const getMockUser2 = () => ({
  id: "userId2",
  uid: "gjgsfioTESSF",
  name: "Yamada",
  target_amount: 200000,
  created_at: new Date(),
  updated_at: new Date(),
});

export const getUsersMSW = () => [
  rest.get("*/user", (_req, res, ctx) => {
    return res(ctx.json(getMockUser1()));
  }),
];
