/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * payreco
 * API for payreco app
 * OpenAPI spec version: 1.0
 */
import { rest } from "msw";
import { faker } from "@faker-js/faker";
import { addHours, startOfToday, subDays } from "date-fns";

export const getGetWorksMock = () =>
  Array.from(
    { length: faker.datatype.number({ min: 1, max: 10 }) },
    (_, i) => i + 1
  ).map((_, i) => ({
    id: faker.random.word(),
    date: subDays(startOfToday(), i),
    starting_time: addHours(subDays(startOfToday(), i), 8),
    ending_time: addHours(subDays(startOfToday(), i), 16),
    break_time: 60,
    working_hours: 7.0,
    pay_amount: 70,
    memo: "メモ" + i,
    user_id: "userId",
    company_id: faker.helpers.arrayElement([
      "companyId1",
      "companyId2",
      "companyId3",
    ]),
    created_at: faker.random.word(),
    updated_at: faker.random.word(),
  }));

export const getWorksMSW = () => [
  rest.get("*/works", (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, "Mocked status"),
      ctx.json(getGetWorksMock())
    );
  }),
];
