/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * payreco
 * API for payreco app
 * OpenAPI spec version: 1.0
 */

/**
 * Company model
 */
export interface Company {
  readonly id: string;
  name: string;
  hourly_wage_system: boolean;
  wage?: number;
  currency: string;
  user_id: string;
  readonly created_at?: Date;
  readonly updated_at?: Date;
}
