/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * payreco
 * API for payreco app
 * OpenAPI spec version: 1.0
 */
import type { ExchangeRateExchangeRateList } from "./exchangeRateExchangeRateList";

export interface ExchangeRate {
  readonly id: number;
  year_and_month: number;
  exchange_rate_list: ExchangeRateExchangeRateList;
}
