/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * payreco
 * API for payreco app
 * OpenAPI spec version: 1.0
 */

export type WorkCompany = {
  name?: string;
  hourly_wage_system?: boolean;
  wage_amount?: number;
  currency_type?: string;
};
